---
title: ""
output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: false
header-includes:
  - \usepackage{geometry}
  - \geometry{a4paper, top=3cm, left=3cm, right=2cm, bottom=2cm}
  - \usepackage{setspace}
  - \usepackage{titling}
fontsize: 12pt
geometry: a4paper
---

```{=tex}
\begin{titlepage}
\begin{center}

{\normalsize \textbf{UNIVERSIDADE FEDERAL DO PARANÁ}}\\

\vspace*{5cm}

{\normalsize HELEN EDUARDA DOS SANTOS LOURENÇO}\\
{\normalsize VITOR NICKHORN KROEFF}

\vspace*{3.5cm}

{\large \textbf{AVALIAÇÃO DA MCA E VARIÁVEIS SUPLEMENTARES}}

\vfill

{\normalsize Curitiba}\\
{\normalsize 2025}

\end{center}
\end{titlepage}
```
```{=tex}
\begin{titlepage}
\begin{center}

{\normalsize HELEN EDUARDA DOS SANTOS LOURENÇO}\\
{\normalsize VITOR NICKHORN KROEFF}

\vspace*{5cm}

{\large \textbf{AVALIAÇÃO DA MCA E VARIÁVEIS SUPLEMENTARES}}

\vspace*{4cm}

\begin{flushright}
\parbox{0.5\textwidth}{
{\normalsize
Trabalho apresentado à disciplina CE318 – Aprendizado não Supervisionado, do Curso de Graduação em Estatística da Universidade Federal do Paraná, como requisito para composição parcial da nota.
}
}
\end{flushright}

\vspace{1cm}

\begin{flushright}
\parbox{0.5\textwidth}{
{\normalsize
Prof. Dr. Anderson Luiz Ara Souza
}
}
\end{flushright}

\vfill

{\normalsize Curitiba}\\
{\normalsize 2025}

\end{center}
\end{titlepage}
```
\tableofcontents

\newpage

# 1 DADOS

\newpage

# 2 MCA
Entre as principais técnicas de análise de dados multivariados, destaca-se a Análise de Correspondência Múltipla (MCA), que é uma extensão da Análise de Correspondência Simples (CA). A MCA é aplicada a dados categóricos com o objetivo de reduzir a dimensionalidade e representar, de forma visual e simplificada, as relações entre os indivíduos e as categorias.

A Análise de Correspondência Múltipla se baseia na construção de um novo sistema de coordenadas, obtido por meio de uma transformação linear das variáveis.

A fórmula


$$ BLA \\ BLA \\ BLA$$

## Variáveis Suplementares

Uma parte importante da análise de correspondência Múltipla é a inclusão de elementos suplementares. Esses elementos não são inclusos no cálculo dos vetores F e G, mas são utilizadas para adicionar informação a análise, principalmente na parte gráfica.


\newpage

# REFERÊNCIAS

Lê, S., Josse, J., & Husson, F. (2008). FactoMineR: An R Package for Multivariate Analysis. *Journal of Statistical Software*, *25*(1), 1–18. <https://doi.org/10.18637/jss.v025.i01>
